### ISSUE TITLE
what about material design icons?

### ISSUE THREAD

**Issue by 1ucay** [kucrut/wp-menu-icons#108]
what about material design icons?

**Comment by kucrut** [comment]
Unfortunately, Material Design Icons are released under Apache 2.0 License, which is not compatible with GPL 2 which this plugin is realeased under.

However, you can create your own set of MDI with Fontello and add them to Menu Icons. See the "How do I add an icon pack from Fontello" section on the plugins [FAQ](https://wordpress.org/plugins/menu-icons/#faq).
