### ISSUE TITLE
Setting the alt attribute

### ISSUE THREAD

**Issue by mstudioIL** [kucrut/wp-menu-icons#111]
I asked about this on the plugin page, and I asking here also (I need to ask here or the plugin page?)
The question is:
How I can set the alt attribute for the image?
Setting the title attribute can also be nice

**Comment by kucrut** [comment]
Hey!

Asking here or on the forums is fine. I just hadn't been able to check the any because of work :)

Anyway,
To set the alt text, you can go to the Media screen, find the image that you use as the icon there and set the alt text. Menu Icons will then automatically use that.

**Comment by mstudioIL** [comment]
Great, thanks for the answer
