### ISSUE TITLE
Custom flag  icons

### ISSUE THREAD

**Issue by joandurand** [kucrut/wp-menu-icons#112]
Hi,

I need to have a US and UK flag. How do I get those added?
![ukflag96](https://user-images.githubusercontent.com/31288412/29630680-9af8e784-8802-11e7-8d6f-1ba344ef8046.jpg)
![usflag_96](https://user-images.githubusercontent.com/31288412/29630679-9af32100-8802-11e7-919e-234e7394b635.jpg)

**Comment by kucrut** [comment]
You can use the "Image" type. Make sure to enable it first from the "Menu Icons Settings" metabox on the left hand side of Menus page.
