### ISSUE TITLE
Feature: only include necessary icon CSS

### ISSUE THREAD

**Issue by richrd** [kucrut/wp-menu-icons#34]
Thx for the great plugin! I focus a lot on speed when I develop websites, and while optimizing I noticed that wp-menu-icons loads CSS for all icon types even if only one type is used. It would be nice if I could manually choose which types are enabled, or if it could be automatically detected. I can also volunteer to implement this if necessary.

**Comment by kucrut** [comment]
@richrd You can disable to icons you don't need by unchecking them in the *Menu Icons Settings* metabox when you're on the *Menus* screen. If you're not seeing the metabox, please enable it first from the *Screen Options* pull-down on the top-right of the screen.

**Comment by richrd** [comment]
Oh, great! Thanks for clarifying this :+1:

**Comment by richrd** [comment]
Great! Thanks for clarifying this :+1:
