### ISSUE TITLE
Doesn't work the option 'Hide Label' with WordPress Theme Virtue by Kadence

### ISSUE THREAD

**Issue by gregovilte** [kucrut/wp-menu-icons#36]
you could tell me any suggestions. thanks

**Comment by kucrut** [comment]
Thanks for reporting this @gregovilte. I'll debug the issue as soon as I can.

**Comment by gregovilte** [comment]
I have tried to solve the problem by modifying: 'type-image.php' in line: $ t_class = ! empty ( $ values ​​[' hide_label ']) ? ' visuallyhidden ': '' ;  with 'hidden'  and achieve it work.
