### ISSUE TITLE
[Feature Request] Add Ionicons icons

### ISSUE THREAD

**Issue by ste93cry** [kucrut/wp-menu-icons#54]
It would be great to have support for the [Ionicons](http://ionicons.com) icons pack. This plugin is fantastic, keep up the good work!

**Comment by richrd** [comment]
:+1:

**Comment by kucrut** [comment]
I think there are enough font icon packs already. To add more, you can simply add them yourself. It's pretty easy actually, please watch this video:

https://www.youtube.com/watch?v=B-5AVwgPaiw

By the way, the latest version brings in support for SVG icons :)
