### ISSUE TITLE
[Feature Request] Enable icons for widgets

### ISSUE THREAD

**Issue by ste93cry** [kucrut/wp-menu-icons#55]
It would be great to have this plugin for widgets too. I don't know if this is in the roadmap or if you already planned it, but I woild really like to see it.

**Comment by kucrut** [comment]
@ste93cry Can you explain the use case for this?

**Comment by ste93cry** [comment]
On the project I was working on when I opened this issue I had a list of widget showing on the page, each with its own icon. I can certainly find other methods to add a field to the widget and let the user choose the icon, maybe with a text input where he has to write the class of the icon to show. However, having a wonderful UI like the one of your plugin is much better. The same applies to the categories. Having a plugin like yours that works for both taxonomies and widgets would be the great imho. I often need to add images/icons to the categories, and under some circumnstances to widgets too.

**Comment by kucrut** [comment]
Ah, so what you need is an icon selector that can be used for virtually anything. Is that correct?

**Comment by ste93cry** [comment]
Yes, it could be useful virtually for anything. It could even be a Advanced Custom Fields type, the only downside is that users would have to download the whole plugin as dependency of yours. This is why I was thinking about extending your plugin to work only with taxonomies (WordPress 4.4+ will have at some point the taxonomy metadata and there is already a great plugin that seems to be compatible with what will be official at some point) and with widgets

**Comment by kucrut** [comment]
Cool. Separating the icon selector from the plugin is inevitable since we're moving to customizer. So yeah, I'll find some time after releasing 0.8.0 to do this.

**Comment by ste93cry** [comment]
Thank you, I really appreciate your efforts to consider this feature request! I love this plugin!

**Comment by kucrut** [comment]
@ste93cry Please check out the [Icon Picker](https://github.com/kucrut/wp-icon-picker) plugin. To know how to use it in your plugin/theme, check out the [icon-picker-integration](https://github.com/kucrut/wp-menu-icons/tree/icon-picker-integration) branch.

**Comment by ste93cry** [comment]
Thank you!
