### ISSUE TITLE
Exclude icon from menu title

### ISSUE THREAD

**Issue by Wouter125** [kucrut/wp-menu-icons#56]
Hi,

I've already opened a topic on stackoverflow which can be found here: 
http://stackoverflow.com/questions/32014149/custom-walker-menu-and-menu-icon

Also some code on what I'm trying to achieve can be found in the topic above! Below I'm having a short description of my problem. If you need any more information, just ask and I'll provide it.

What I really want to accomplish is some custom classes around the icon without breaking the plugin. Right now it is automatically embedded within the $title element. I want it separated from my menu title so i can do some custom css on it! I'm using a custom SVG image by the way!

Could you point me in the direction on how to do this? Thanks in advance.

Kind regards,

Wouter

**Comment by kucrut** [comment]
@Wouter125 When version 0.8.0 is released, you will be able to [hook into the `menu_icons_item_title` filter](https://github.com/kucrut/wp-menu-icons/blob/develop/includes/type.php#L273) and do your thing there.
