### ISSUE TITLE
Switch off icon set by default but not permanent disable

### ISSUE THREAD

**Issue by NateWr** [kucrut/wp-menu-icons#64]
This looks really great, and thanks so much for making it highly extensible. I'm thinking about adding it into a theme I'm developing at the moment.

What I'd like to do is "turn off" most icon sets by default, to guide my customers to the icons I think they'll want. But I don't want to completely remove the various options, if they want to dig in and enable one.

Ideally, I'm looking for a way to simply make the checkboxes in the Menu Icons Settings unchecked by default. So all but my custom icon set is inactive, but the others are there if they want to activate them.

It seems like the `menu_icons_menu_settings` ought to be where I hook in, but as far as I can tell my only option is to add a `disabled` key which will hide it completely.

Is there any way for to change the default settings, so that they're disabled by default, without losing those checkboxes so that customers can re-enable them if desired?

**Comment by kucrut** [comment]
@NateWr The `menu_icons_settings_defaults` will be available in the next version. If you'd like to try it our now, you can check out the `icon-picker-integration` branch (don't forget to udpate the submodules afterwards). For example, make Elusive Icons type the only active type by default:

```php
add_filter( 'menu_icons_settings_defaults', function( $settings ) {
	$settings['global']['icon_types'] = array( 'elusive' );
	return $settings;
});
```

**Comment by NateWr** [comment]
Thanks @kucrut, that's great news!
