### ISSUE TITLE
[Feature Request] Register repository as Composer package

### ISSUE THREAD

**Issue by vburlak** [kucrut/wp-menu-icons#65]
Hi @kucrut
First, thanks for a great plugin.

Please, can you register that plugin as composer package at [packagist](https://packagist.org)?
It will be great to use it in projects that uses composer as package manager for wp plugins/libraries. 
Cheers!

**Comment by kucrut** [comment]
This is ready on [Packagist](https://packagist.org/packages/kucrut/menu-icons), but please use version `0.9.1` because it contains a fix for missing dependency (Icon Picker).

**Comment by vburlak** [comment]
great, thanks!
