### ISSUE TITLE
[Performance Issue] New Menu Item sorting performance issue in Google Chrome

### ISSUE THREAD

**Issue by vburlak** [kucrut/wp-menu-icons#66]
Hi, @kucrut 
I found a strange issue.
Short description: When Menu Icons plugin used with all Icon Typed defined in Menu Icons Settings — it's causes performance issue when sorting Menu Items after adding New Menu Item to existing menu items list. This problem is most visible in Google Chrome (not tested in Firefox and Opera). In Safari — all looks great, and sorting works without "glitch"

How to reproduce the issue:
1. Use Google Chrome, 
2. Add some menu elements in menu location. Save menu location.
3. Enable all Icon Types in Menu Icons Settings and Save changes.
4. Add new Menu Item to that menu location.
5. And **without** Saving changes in menu location try to make any sorting of  Menu Items (existing item or just added new item)
In this case, all the menu items will have performance issues during sorting event.

I did 4 tests and captured some screencast, that reproduces that problem. it's available here: https://www.youtube.com/watch?v=ur1A4IiTQRc 
Make sure, you have enabled annotation on youtube. I written some comments over my screencast, that can be helpful in describing my tests.
My test enviroument: Mac OS X 10.11, Google Chrome 46, Wordpress 4.3.1, latest WP Menu Icons plugin, and using Twenty Fifteen theme.

- Test 1: How sorting event works without WP Menu Icons plugin
  - Step 1: Soritng existing item - **good**
  - Step 2: Sorting any Menu Item after adding New Menu Item - **good**
- Test 2: How sorting event works with WP Menu Icons plugin and all icon types defined in Menu Icons Settings.
  - Step 1: Soritng existing item - **good**
  - Step 2: Sorting any Menu Item after adding New Menu Item - **bad, performance issue**
- Test 3: How sorting event works with WP Menu Icons plugin without external icon types(such as glyphicons, elusivicons and etc.)(only with Dashicons and image/svg)
  - Step 1: Soritng existing item - **good**
  - Step 2: Sorting any Menu Item after adding New Menu Item - **good, no performance issue**
- Test 4: How sorting event works on existing item (loaded on page load) with external icons(glyphicons, elusivicons).
  - Step 1: Soritng existing item with previously defined Menu Icon - **good**
  - Step 2: Sorting existing item with added Elusive Icon - **good, no performance issue**
  - Step 3: Sorting any Menu Item after adding New Menu Item - **bad, performance issue for all Menu Items**

As you can see on screencast, performance problem appears when you use all the icon types and **only after adding** a new Menu Item to the Menu Items List.

I'm tried to refactor `wp-menu-icons/js/admin.js` file and find what causes the problem. But I did not find anything what can cause that problem. 
Maybe you will have once the idea of ​​what may be a problem, and hope that it will be easy to fix.

P.S. I'm tested in on three different MacBook Pro and one iMac in Google Chrome on Mac OS X. Everywhere problem was reproduced.
P.S.S Later, i will try to test in in Google Chrome on Windows. Just interested.

Cheers!

**Comment by kucrut** [comment]
@vburlak Thank you for the very detailed report. I really appreciate it.

I'm currently in the middle of rebuilding the plugin (almost finished actually), and I'd really appreciate it even more if you could test it and see if this issue persists:
* Check out the `icon-picker-integration` branch
* Update submodules, eg: `git submodule update --init --recursive`

Thanks!

**Comment by kucrut** [comment]
Also, feel free to file additional issues you found when doing the testing, especially the ones related to backward-compatibility.

**Comment by vburlak** [comment]
@kucrut Thank you for fast reply.

I just checked out branch `icon-picker-integration`. 
That branch doesn't have such performance issue and everything works how it should be. That's great!
Also, i checked `icon-picker-integration` commit history. You did a great job!

One moment. In my enviroument, i'm also testing plugin with Image defined as Menu Icon. 
And аfter i'm checked out to `icon-picker-integration` and updated submodules, i got warning message: 
```
Fatal error: Call to undefined function wp_get_attachment_image_url() in /Users/vburlak/sites/tfstation/public_html/wp-content/plugins/wp-menu-icons/includes/meta.php on line 96
```

**Comment by vburlak** [comment]
I think you mean `wp_get_attachment_image_src ` instead of `wp_get_attachment_image_url `.
Replaced line 96 in /includes/meta.php with

```php
$image_attributes = wp_get_attachment_image_src( $value['icon'], 'thumbnail', false );
if( $image_attributes ){
	$value['url'] = $image_attributes[0];
}
```
And the problem was resolved.

**Comment by kucrut** [comment]
Oh dear. Thank you for that. The `wp_get_attachment_image_url()` is newly introduced in 4.4.0. I'll fix it asap.

I guess we can close this issue then?

**Comment by vburlak** [comment]
@kucrut whoah. Haven't enough time to read, whats new in 4.4.0.
Yep, thx for your time! Closing.
