### ISSUE TITLE
Icon selection menu no longer allows to select attachment files.

### ISSUE THREAD

**Issue by themiguelamador** [kucrut/wp-menu-icons#68]
After last update, I lost the ability to select other type of icon sources, namely the attachment media...
Previously set icon this way also vanished. 

<img width="1226" alt="screen shot 2015-11-17 at 08 08 11" src="https://cloud.githubusercontent.com/assets/2944764/11205793/623c572a-8d02-11e5-9056-e9df18de8f97.png">

**Comment by kucrut** [comment]
@themiguelamador Please see [this post](https://wordpress.org/support/topic/icons-functionality-removed-in-latest-update?replies=11#post-76718190).
