### ISSUE TITLE
How can I import a iconset from a CDN?

### ISSUE THREAD

**Issue by korra8888** [kucrut/wp-menu-icons#70]
How can I import a iconset from a CDN for improving site performance? example font-awesome CDN or my custom iconset uploaded into a cdn. I would like to avoid to store my custom icon set into fontpacks folder. Thanks!

**Comment by kucrut** [comment]
You'll be able to load css files from CDN in [the next version](https://github.com/kucrut/wp-icon-picker/commit/47193293a64fc962921de56e240ee23a7cfc1adf).
