### ISSUE TITLE
Icons Don't Appear on Social Menu

### ISSUE THREAD

**Issue by acug01** [kucrut/wp-menu-icons#71]
Icon field and placement both show up in WP Menu Structure tool, but icons do not show up on Social Menu. Theme is WEN Corporate. Icons do work if Menu is placed elsewhere, e.g., in Footer.

**Comment by kucrut** [comment]
Correct. *Wen Corporate* has a special implementation on the *social* menu location which prevents Menu Icons from doing its job.
