### ISSUE TITLE
Conflict issues with "Nav Menu Roles" plugins

### ISSUE THREAD

**Issue by herianti** [kucrut/wp-menu-icons#72]
Can you fix the conflict issues with "Nav Menu Roles" plugins..
Thank you very much.. :)
![2016 02 13 04-29-47 -- error plugin nav user role](https://cloud.githubusercontent.com/assets/17208756/13023385/0d6b6cdc-d21b-11e5-91fa-a753fc146ae3.jpg)

**Comment by kucrut** [comment]
I believe this is only a warning, [as reported in the forums](https://wordpress.org/support/topic/conflict-with-nav-menu-roles-plugin-2?replies=7).
