### ISSUE TITLE
adding dynamic links with the icon

### ISSUE THREAD

**Issue by saltnpixels** [kucrut/wp-menu-icons#75]
im trying to add a dynamic link into the menu but i dont think i can add the menu icon that way...
i tried the nav walker but i lose the icon. 
Is there a hook to somehow change the url for an item so ican dynamically add a link?

**Comment by kucrut** [comment]
Hi @saltnpixels 

Could you paste here the code you're using to inject the dynamic menus?

**Comment by saltnpixels** [comment]
it got too difficult for me so I ended up using a sort of trick!
if you create a menu item of a link and the link is --url-- it will string replace for a dynamic url
see here what i did.
https://gist.github.com/saltnpixels/5375ea9d629c0737a52e1ad4f834da97

**Comment by kucrut** [comment]
Cool. Thanks for sharing the code @saltnpixels!
