### ISSUE TITLE
disable wp_enqueue_scripts

### ISSUE THREAD

**Issue by dacopan** [kucrut/wp-menu-icons#76]
Hi, When I develop a theme I include icon sets, for example in my latest theme I include Font Awesome, and when I active your plugin added another font awesome.

Please add a setting to disable the wp_enqueue_scripts in your plugin.

**Comment by kucrut** [comment]
That [shouldn't happen](https://github.com/kucrut/wp-icon-picker/blob/master/includes/types/font.php#L89-L114). When there's already a stylesheet registered, *Icon Picker* will compare the versions and only register its own stylesheet if it has greater version number.
