### ISSUE TITLE
No icons when too many menu items

### ISSUE THREAD

**Issue by KrummenHacker** [kucrut/wp-menu-icons#79]
When I try to add icons to first level menu items when the the menu has a lot of subitems (~100 and it will grow in the future), the icons are not saved for the last items in the first level. I didn't try to add icons to subitems. When I add an icon on a item at the top of the list, it is OK. But as soon as I move that item to the bottom of the list, the icon is removed.

It looks like you are using a fixed sized array to store the icon IDs and that I overflown that limit in my usage.Is it possible to set this limit to a higher value, like 256, or to remove that limit one and for all?

**Comment by kucrut** [comment]
This is related to your PHP settings. See
https://wordpress.org/support/topic/menu-size-limit
https://core.trac.wordpress.org/ticket/14134
