### ISSUE TITLE
Missing "fa-rrs" and "fa-rrs-square"

### ISSUE THREAD

**Issue by DiamondPigman** [kucrut/wp-menu-icons#80]
![image](https://cloud.githubusercontent.com/assets/14424577/15366135/d89eeb14-1d1a-11e6-9369-e1c14d13d22b.png)

**Comment by kucrut** [comment]
I believe what you *really* want is `fa-rss` and `fa-rss-square`.

**Comment by DiamondPigman** [comment]
Man I am dumb
