### ISSUE TITLE
Issue with font awesome

### ISSUE THREAD

**Issue by mirarosen** [kucrut/wp-menu-icons#82]
My theme use font awesome as main font so when buttons like scroll up och social medias will not work when I active Menu Icons.

And I really like your plug in but cant use it when I dont know how to fix this issue because it comes in many places of the website. I will attach a screen shot of just showing how it looks when want to ad icons on the website. But its more places but cant take a screen shot of it because it will just be invisible where the "icon" of for example go to the social media page. And the the issue I understand it comes together is because my theme use as well awesome font.
Here is the site. The scrolling up button is now not working its just an grey area because of it (of you scroll down you will see it)
http://www.whywait.nu/psbbackup/

And here is the screen shot of when want to add an icon in the page that they are "gone"
![screen shot 2016-06-09 at 12 19 26](https://cloud.githubusercontent.com/assets/16241013/15926815/3acadfa8-2e3e-11e6-907e-db5518de6c7e.png)

Thanks,
Mira

**Comment by mirarosen** [comment]
Sorry I took the worng screen shot. Here is with font awasome

![screen shot 2016-06-09 at 12 19 13](https://cloud.githubusercontent.com/assets/16241013/15926842/5e8c65ce-2e3e-11e6-95e4-ff805c289803.png)

**Comment by kucrut** [comment]
Let me know if you're still having the issue and feel free to re-open it.
