### ISSUE TITLE
Doesn't work in WP 4.5.3

### ISSUE THREAD

**Issue by thybzi** [kucrut/wp-menu-icons#84]
Installed plugin on WP 4.5.3 (plugin installer says it is compatible) and activated it.
Cannot see any changes in menu admin section (nothing about icons or pictures when editing my menus and their field settings).
Also cannot see Menu Icons Settings metabox.
Am I doing something wrong?
Thank you in advance.

**Comment by kucrut** [comment]
@thybzi Make sure the *Menu Icons Settings* checkbox on *Screen Options* is ticked. Also, please try with a default theme and without any other plugins activated.

**Comment by thybzi** [comment]
Ah, I didn't look for this checkbox on _Screen Options_
I'll try this and report back.

**Comment by thybzi** [comment]
Now I see, default theme has _Menu_ admin subsection in left column, within its Screen Settings I can see the checkbox.
My custom theme doesn't have _Menu_ as separate subsection, menu editing is only available through _Customize_.
So that should be no problem of plugin, but a problem of my custom theme.
I'll try to find out, but this ticket should be closed.

**Comment by thybzi** [comment]
My custom theme was missing `register_nav_menus()` call in `functions.php`
Default theme has it like the following:
```php
	// This theme uses wp_nav_menu() in two locations.
	register_nav_menus( array(
		'primary' => __( 'Primary Menu', 'twentysixteen' ),
		'social'  => __( 'Social Links Menu', 'twentysixteen' ),
	) );
```

After adding similar block to my theme's `functions.php`, I got WP Menu Icons working.
Thanks!
