### ISSUE TITLE
Not compatible with PHP 7

### ISSUE THREAD

**Issue by theangeleyes** [kucrut/wp-menu-icons#88]
This great plugin is unfortunately not compatible with PHP's latest version. Kindly update it. It has not been updated in a long time, and causes errors when used with PHP's current version.

Kind regards,
FW

**Comment by kucrut** [comment]
I'm actually using PHP7 and am not seeing errors. Are you able to list here the exact errors you're getting? I'm planning on pushing an update this weekend.
