### ISSUE TITLE
Incompatible with WP4.7

### ISSUE THREAD

**Issue by helgatheviking** [kucrut/wp-menu-icons#91]
The options aren't showing up any longer in 4.7. I suspect it is your [`preg_replace()`](https://github.com/kucrut/wp-menu-icons/blob/develop/includes/library/walker-nav-menu-edit.php#L40-L45). The `preg_replace()` was clever! I thought about trying it in Nav Menu Roles, but regex is kinda voodoo for me, and I couldn't figure it out.

**Comment by aaronkirkham** [comment]
Fixed in my pull request, https://github.com/kucrut/wp-menu-icons/pull/92
