### ISSUE TITLE
Custom action hook parameters are not the same as in Nav Menu Roles

### ISSUE THREAD

**Issue by helgatheviking** [kucrut/wp-menu-icons#94]
First, I love the `preg_replace()` idea! And two, thanks for adding the `wp_nav_menu_item_custom_fields` action hook so Nav Menu Roles and Menu Icons can be compatible.

However, I've found that your action hook's params aren't the same as mine. 

You have:
    do_action( 'wp_nav_menu_item_custom_fields', $id, $item, $depth, $args );

While I have:
     do_action( 'wp_nav_menu_item_custom_fields', $item_id, $item, $depth, $args );

In your case `$id` will always be zero. I don't know if this has a lot of impact since it's only used by us menu plugin authors, but I thought I'd point it out.

**Comment by kucrut** [comment]
Sorry it took me so long to get to this. I've moved the issue to [Menu Item Custom Fields](https://github.com/kucrut/wp-menu-item-custom-fields/issues/12).
